# Generated by Django 4.2.5 on 2023-09-30 18:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gwiji_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('None', 'None'), ('Tech and Innovations', 'Tech and Innovations'), ('Creative Works', 'Creative Works'), ('Fashion and Wearables', 'Fashion and Wearables'), ('Health and Fitness', 'Health and Fitness'), ('Energy and Green Tech', 'Energy and Green Tech')], default='None', max_length=100)),
                ('current_raise', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('date_start', models.DateTimeField(default=datetime.datetime.now)),
                ('date_end', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='current_raise',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='total_raised',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('Entrepreneur', 'Entrepreneur'), ('Investor', 'Investor')], default='Entrepreneur', max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(blank=True, upload_to='post_images')),
                ('no_post_likes', models.IntegerField(default=0)),
                ('no_post_views', models.IntegerField(default=0)),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
                ('campaign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='gwiji_app.campaigns')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwiji_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='gwiji_app.profile')),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='gwiji_app.posts')),
            ],
        ),
        migrations.AddField(
            model_name='campaigns',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='gwiji_app.profile'),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='gwiji_app.projects'),
        ),
    ]
