# Generated by Django 4.2.5 on 2023-09-30 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0002_campaigns_remove_projects_current_raise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='gwiji_app.profile'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_board',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='tagline',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
