# Generated by Django 4.2.5 on 2023-09-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0003_campaigns_featured_projects_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_board',
            field=models.TextField(blank=True),
        ),
    ]
