# Generated by Django 4.2.5 on 2023-09-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0004_alter_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='campaign_image',
            field=models.ImageField(blank=True, upload_to='campaign_images'),
        ),
    ]
