# Generated by Django 4.2.5 on 2023-09-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0005_campaigns_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='percentage_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
