# Generated by Django 4.2.5 on 2023-09-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0006_campaigns_percentage_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='category',
            field=models.CharField(choices=[('Tech and Innovations', 'Tech and Innovations'), ('Creative Works', 'Creative Works'), ('Fashion and Wearables', 'Fashion and Wearables'), ('Health and Fitness', 'Health and Fitness'), ('Energy and Green Tech', 'Energy and Green Tech')], max_length=100),
        ),
    ]
