# Generated by Django 4.2.5 on 2023-09-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0007_alter_campaigns_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='no_post_comments',
            field=models.IntegerField(default=0),
        ),
    ]
