# Generated by Django 4.2.5 on 2023-10-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0011_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='website',
            field=models.CharField(default='gwiji.io', max_length=100),
        ),
    ]
