# Generated by Django 4.2.5 on 2023-10-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0012_projects_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('campaign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_campaigns', to='gwiji_app.campaigns')),
            ],
        ),
    ]
