# Generated by Django 4.2.5 on 2023-10-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0013_boardquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='prototype',
            field=models.FileField(default='', upload_to='prototypes'),
        ),
    ]
