# Generated by Django 4.2.5 on 2023-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0014_projects_prototype'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='financials_doc',
            field=models.FileField(default='', upload_to='financials_doc'),
        ),
        migrations.AddField(
            model_name='projects',
            name='legals_doc',
            field=models.FileField(default='', upload_to='legals_doc'),
        ),
        migrations.AddField(
            model_name='projects',
            name='market_research',
            field=models.FileField(default='', upload_to='market_research_doc'),
        ),
        migrations.AddField(
            model_name='projects',
            name='pitch_deck',
            field=models.FileField(default='', upload_to='pitch_decks'),
        ),
    ]
