# Generated by Django 4.2.5 on 2023-10-02 21:59

from django.db import migrations, models
import gwiji_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0016_projects_operational_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('linkedin', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='campaigns',
            name='pack_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='roadmap',
            field=gwiji_app.models.ScaleField(default=1),
        ),
        migrations.AddField(
            model_name='projects',
            name='shareperdollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='gwiji_app.team'),
        ),
    ]
