# Generated by Django 4.2.5 on 2023-10-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0017_team_campaigns_pack_type_projects_roadmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='dp',
            field=models.ImageField(blank=True, upload_to='team_member_dp'),
        ),
    ]
