# Generated by Django 4.2.5 on 2023-10-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0018_team_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='roadmap',
            field=models.CharField(choices=[('Idea Conception', 'Idea Conception'), ('Market Research', 'Market Research'), ('Business Plan Creation', 'Business Plan Creation'), ('Prototyping', 'Prototyping'), ('MVP Development', 'MVP Development'), ('Initial Customer Acquisition', 'Initial Customer Acquisition'), ('Seed Funding Preparation', 'Seed Funding Preparation'), ('Pitching to Investors', 'Pitching to Investors'), ('Seed Funding Secured', 'Seed Funding Secured'), ('Scaling Operations', 'Scaling Operations')], default='Idea Conception', max_length=50),
        ),
    ]
