# Generated by Django 4.2.5 on 2023-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0021_alter_projects_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='financials_doc',
            field=models.FileField(blank=True, default='', upload_to='financials_doc'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='legals_doc',
            field=models.FileField(blank=True, default='', upload_to='legals_doc'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='market_research',
            field=models.FileField(blank=True, default='', upload_to='market_research_doc'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='operational_doc',
            field=models.FileField(blank=True, default='', upload_to='market_research_doc'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pitch_deck',
            field=models.FileField(blank=True, default='', upload_to='pitch_decks'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='prototype',
            field=models.FileField(blank=True, default='', upload_to='prototypes'),
        ),
    ]
