# Generated by Django 4.2.5 on 2023-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0022_alter_projects_financials_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_campaigns', to='gwiji_app.campaigns'),
        ),
    ]
