# Generated by Django 4.2.5 on 2023-10-03 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0025_profile_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
