# Generated by Django 4.2.5 on 2023-10-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0026_profile_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='logo',
            field=models.ImageField(blank=True, upload_to='project_logos'),
        ),
    ]
