# Generated by Django 4.2.5 on 2023-10-03 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0027_projects_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date_started',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('sharesperdollar', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='gwiji_app.campaigns')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwiji_app.profile')),
            ],
        ),
    ]
