# Generated by Django 4.2.5 on 2023-10-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0028_projects_date_started_projects_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
