# Generated by Django 4.2.5 on 2023-10-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0029_rename_city_profile_location_remove_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default-dp.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='default-cover.png', upload_to='profile_cover'),
        ),
    ]
