# Generated by Django 4.2.5 on 2023-10-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0030_alter_profile_avatar_alter_profile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='campaign',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='gwiji_app.campaigns'),
        ),
    ]
