# Generated by Django 4.2.5 on 2023-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0032_alter_posts_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='profile_likes', to='gwiji_app.profile'),
        ),
    ]
