# Generated by Django 4.2.5 on 2023-10-04 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0033_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
