# Generated by Django 4.2.5 on 2023-10-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0034_comments_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post_comments', to='gwiji_app.comments'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='gwiji_app.profile'),
        ),
    ]
