# Generated by Django 4.2.5 on 2023-10-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0035_posts_comments_alter_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='investments',
            field=models.ManyToManyField(blank=True, related_name='investments', to='gwiji_app.investments'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invested_campaign', to='gwiji_app.campaigns'),
        ),
    ]
