# Generated by Django 4.2.5 on 2023-10-05 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0036_campaigns_investments_alter_investments_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
