# Generated by Django 4.2.5 on 2023-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0037_investments_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investments',
            old_name='sharesperdollar',
            new_name='sharesperdollar_buying',
        ),
        migrations.RenameField(
            model_name='investments',
            old_name='amount',
            new_name='total_shares',
        ),
        migrations.RenameField(
            model_name='investments',
            old_name='shares',
            new_name='total_value_buying',
        ),
        migrations.AddField(
            model_name='investments',
            name='sharesperdollar_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='investments',
            name='total_value_current',
            field=models.IntegerField(default=0),
        ),
    ]
