# Generated by Django 4.2.5 on 2023-10-05 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0038_rename_sharesperdollar_investments_sharesperdollar_buying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
