# Generated by Django 4.2.5 on 2023-10-05 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0039_alter_investments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
