# Generated by Django 4.2.5 on 2023-10-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0041_remove_campaigns_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='category',
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('Tech and Innovations', 'Tech and Innovations'), ('Creative Works', 'Creative Works'), ('Fashion and Wearables', 'Fashion and Wearables'), ('Health and Fitness', 'Health and Fitness'), ('Energy and Green Tech', 'Energy and Green Tech')], default='Tech and Innovations', max_length=100),
        ),
    ]
