# Generated by Django 4.2.5 on 2023-10-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0042_remove_campaigns_category_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='status',
            field=models.CharField(choices=[('Review', 'Review'), ('Active', 'Active')], default='Review', max_length=100),
        ),
    ]
