# Generated by Django 4.2.5 on 2023-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0043_campaigns_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='status',
            field=models.CharField(choices=[('In Review', 'In Review'), ('Active', 'Active')], default='In Review', max_length=100),
        ),
    ]
