# Generated by Django 4.2.5 on 2023-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0044_alter_campaigns_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_board',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_challenges',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_future',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_goals',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_growth',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_impact',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_innovation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_market',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_story',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_team',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='campaign_board_unique',
            field=models.TextField(default=''),
        ),
    ]
