# Generated by Django 4.2.5 on 2023-10-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0045_remove_projects_project_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='incorporated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='gwiji_app.profile'),
        ),
    ]
