# Generated by Django 4.2.5 on 2023-10-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0046_projects_incorporated_alter_projects_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='total_shares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='status',
            field=models.CharField(choices=[('In Review', 'In Review'), ('Active', 'Active'), ('Ended', 'Ended')], default='In Review', max_length=100),
        ),
    ]
