# Generated by Django 4.2.5 on 2023-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0047_projects_total_shares_alter_campaigns_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='document',
            field=models.FileField(blank=True, default='', upload_to='investment_document'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_challenges',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_future',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_goals',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_growth',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_impact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_innovation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_market',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_team',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='campaign_board_unique',
            field=models.TextField(blank=True, default=''),
        ),
    ]
