# Generated by Django 4.2.5 on 2023-10-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0048_investments_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='identification_doc',
            field=models.ImageField(default='', null=True, upload_to='profile_identifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='identification_type',
            field=models.CharField(choices=[('National ID Card', 'National ID Card'), ('International Passport', 'International Passport'), ('Drivers License', 'Drivers License'), ('None', 'None')], default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.CharField(choices=[('Verified', 'Verified'), ('NotVerified', 'NotVerified'), ('Pending', 'Pending')], default='NotVerified', max_length=100),
        ),
        migrations.AlterField(
            model_name='investments',
            name='document',
            field=models.FileField(blank=True, default='', upload_to='investment_ddocument'),
        ),
    ]
