# Generated by Django 4.2.5 on 2023-10-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0050_rename_verified_profile_verification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='legals_doc',
            new_name='incorporation_certificate',
        ),
        migrations.AlterField(
            model_name='profile',
            name='identification_doc',
            field=models.ImageField(blank=True, default='', upload_to='profile_identifications'),
        ),
    ]
