# Generated by Django 4.2.5 on 2023-10-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0051_rename_legals_doc_projects_incorporation_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='valuation_report',
            field=models.FileField(blank=True, default='', upload_to='valuation_reports'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='incorporation_certificate',
            field=models.FileField(blank=True, default='', upload_to='incorporation_certificates'),
        ),
    ]
