# Generated by Django 4.2.5 on 2023-10-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwiji_app', '0052_projects_valuation_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='intented_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
